source "https://rubygems.org"
gemspec

gem "saga_forge", path: ".."

gem "rake"
gem "minitest"
gem "minitest-reporters"
gem "combustion"
gem "rack-test"
gem "rails", ">= 7.1"
gem "sqlite3"
gem "standard"

group :development do
  gem "webrick"
  gem "tailwindcss-ruby", "~> 4.3"
end
